import type { KataConfig } from '@domain/types/config.js';

export interface RegisteredAgent {
  name: string;
  id: string;
  source: string;
}

export interface KataMdOptions {
  config: KataConfig;
  kataDir: string;
  /** Agents populated after `kata init --discover-agents`. */
  registeredAgents?: RegisteredAgent[];
}

/**
 * Generate the content for `.kata/KATA.md` — the project context file
 * that kataka (agents) read at the start of each kiai (execution).
 *
 * The file is generated at `kata init` and refreshed after each cooldown
 * (Wave I will add the cooldown refresh step).
 */
/** Strip pipe characters and newlines to prevent markdown table injection. */
function sanitizeMd(s: string): string {
  return s.replace(/[|\n\r]/g, ' ').trim();
}

function renderKatakaRegistry(agents?: RegisteredAgent[]): string {
  if (!agents || agents.length === 0) {
    return '_No kataka registered. Run `kata init --discover-agents` to auto-register agents._';
  }
  const rows = agents
    .map((a) => `| ${sanitizeMd(a.name)} | ${sanitizeMd(a.id)} | ${sanitizeMd(a.source)} |`)
    .join('\n');
  return `| Name | ID | Source |\n|------|----|---------|\n${rows}`;
}

export function generateKataMd(options: KataMdOptions): string {
  const { config, registeredAgents } = options;
  const projectName = config.project.name ?? 'Unnamed Project';
  const methodology = config.methodology;
  const adapter = config.execution.adapter;
  const experienceLevel = config.user.experienceLevel;
  const synthesisDepth = config.cooldown.synthesisDepth;

  return `# KATA.md — Project Context

> This file is read by kataka (agents) at the start of each kiai (execution session).
> It is generated by \`kata init\` and refreshed after each ma (cooldown).
> Edit the placeholder sections below as your project evolves.

---

## Project

- **Name**: ${projectName}
- **Methodology**: ${methodology}
- **Adapter**: ${adapter}
- **Experience level**: ${experienceLevel}

---

## Active Cycle

<!-- Updated automatically after each cooldown. -->
<!-- Run \`kata cycle status\` to see the current cycle. -->

_No active cycle. Run \`kata cycle new\` to start one._

---

## Kataka Registry

<!-- Populated by \`kata init --discover-agents\`. Re-run to refresh after registering new agents. -->

${renderKatakaRegistry(registeredAgents)}

---

## Methodology Preferences

- **Synthesis depth**: ${synthesisDepth} (controls how deeply cooldown analyses observations)
- **Confidence threshold**: ${config.execution.confidenceThreshold} (decisions below this level require approval)

---

## Project Bunkai (Learnings)

<!-- Updated automatically after each cooldown when high-confidence learnings are synthesized. -->

_No learnings captured yet. Run a full cycle and cooldown to start accumulating bunkai._

---

## Open Gaps

<!-- Gaps captured via \`kata observe record\` with type: gap -->

_No open gaps recorded._

---

*Generated by \`kata init\`. Last updated: ${new Date().toISOString()}*
`;
}
