import type { DojoSession, DojoContentSection } from '@domain/types/dojo.js';
import { tailwindConfig, DOJO_COLORS, DIRECTION_COLORS } from './design-system.js';

export function generateHtml(session: DojoSession): string {
  const nav = generateNav(session);
  const content = generateContent(session);
  const darkModeScript = generateDarkModeScript();

  return `<!DOCTYPE html>
<html lang="en" class="scroll-smooth">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(session.title)} — Dojo</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <noscript><!-- Tailwind CDN requires JavaScript --></noscript>
  <script>${tailwindConfig()}</script>
  <style>
    /* Fallback styles when Tailwind CDN is unavailable */
    @supports not (--tw: 1) {
      body { font-family: system-ui, sans-serif; max-width: 800px; margin: 0 auto; padding: 1rem; }
      nav { display: none; }
      .flex { display: block; }
      details { margin: 1rem 0; }
    }
  </style>
  <style>
    body { background-color: ${DOJO_COLORS.washi}; }
    .dark body { background-color: ${DOJO_COLORS.washiDark}; }
    .dojo-accent { border-left: 3px solid ${DOJO_COLORS.aka}; }
    details summary { cursor: pointer; }
    details summary::-webkit-details-marker { display: none; }
    @media print { .no-print { display: none; } nav { display: none; } }
  </style>
</head>
<body class="text-dojo-ink dark:text-gray-200 min-h-screen">
  <div class="flex">
    ${nav}
    <main class="flex-1 max-w-4xl mx-auto px-6 py-8">
      <header class="mb-10">
        <div class="dojo-accent pl-4">
          <h1 class="text-3xl font-bold tracking-tight">${escapeHtml(session.title)}</h1>
          <p class="text-dojo-stone dark:text-gray-400 mt-1">${escapeHtml(session.summary)}</p>
          <div class="flex gap-4 mt-2 text-sm text-dojo-stone dark:text-gray-500">
            <span>${session.topics.length} topic${session.topics.length !== 1 ? 's' : ''}</span>
            <span>${session.sections.length} section${session.sections.length !== 1 ? 's' : ''}</span>
            <span>${new Date(session.createdAt).toLocaleDateString()}</span>
          </div>
        </div>
        ${session.tags.length > 0 ? `<div class="flex gap-2 mt-3 flex-wrap">${session.tags.map((t) => `<span class="px-2 py-0.5 text-xs rounded-full bg-gray-100 dark:bg-gray-700 text-dojo-stone">${escapeHtml(t)}</span>`).join('')}</div>` : ''}
      </header>
      ${content}
      <footer class="mt-16 pt-8 border-t border-gray-200 dark:border-gray-700 text-sm text-dojo-stone dark:text-gray-500">
        <p>Generated by <strong>kata dojo</strong> — ${new Date(session.createdAt).toISOString()}</p>
      </footer>
    </main>
  </div>
  <script>${darkModeScript}</script>
</body>
</html>`;
}

function generateNav(session: DojoSession): string {
  const directionGroups = new Map<string, typeof session.topics>();
  for (const topic of session.topics) {
    if (!directionGroups.has(topic.direction)) {
      directionGroups.set(topic.direction, []);
    }
    directionGroups.get(topic.direction)!.push(topic);
  }

  let navItems = '';
  for (const [direction, topics] of directionGroups) {
    const color = DIRECTION_COLORS[direction] ?? DOJO_COLORS.stone;
    navItems += `<div class="mb-4">
      <div class="text-xs font-semibold uppercase tracking-wider mb-1" style="color: ${color}">${escapeHtml(direction)}</div>
      ${topics.map((t) => `<a href="#topic-${slugify(t.title)}" class="block px-2 py-1 text-sm text-gray-600 dark:text-gray-400 hover:text-dojo-ink dark:hover:text-white rounded transition-colors">${escapeHtml(t.title)}</a>`).join('')}
    </div>`;
  }

  return `<nav class="no-print sticky top-0 h-screen w-56 shrink-0 border-r border-gray-200 dark:border-gray-700 p-4 overflow-y-auto hidden lg:block">
    <div class="mb-6">
      <button onclick="document.documentElement.classList.toggle('dark')" class="text-xs px-2 py-1 rounded border border-gray-300 dark:border-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 transition-colors">Toggle Dark</button>
    </div>
    ${navItems}
  </nav>`;
}

function generateContent(session: DojoSession): string {
  let currentTopic = '';
  let html = '';

  for (const section of session.sections) {
    if (section.topicTitle !== currentTopic) {
      // Close previous section if one was open
      if (currentTopic) html += '</section>';

      currentTopic = section.topicTitle;
      const topic = session.topics.find((t) => t.title === currentTopic);
      const direction = topic?.direction ?? 'inward';
      const color = DIRECTION_COLORS[direction] ?? DOJO_COLORS.stone;

      html += `<section id="topic-${slugify(currentTopic)}" class="mb-10">
        <div class="flex items-center gap-3 mb-4">
          <div class="w-1.5 h-8 rounded-full" style="background: ${color}"></div>
          <div>
            <h2 class="text-xl font-semibold">${escapeHtml(currentTopic)}</h2>
            ${topic ? `<span class="text-xs uppercase tracking-wider" style="color: ${color}">${escapeHtml(direction)}</span>` : ''}
          </div>
        </div>`;
    }

    html += renderSection(section);
  }

  // Close last section
  if (currentTopic) html += '</section>';
  return html;
}

function renderSection(section: DojoContentSection): string {
  const indent = section.depth > 0 ? `ml-${Math.min(section.depth * 4, 12)}` : '';

  if (section.collapsed) {
    return `<details class="mb-4 ${indent}">
      <summary class="font-medium text-sm cursor-pointer hover:text-dojo-sora transition-colors">
        ${escapeHtml(section.title)}
      </summary>
      <div class="mt-2 p-4 bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
        ${renderSectionContent(section)}
      </div>
    </details>`;
  }

  return `<div class="mb-4 ${indent} p-4 bg-white dark:bg-gray-800 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
    <h3 class="font-medium text-sm mb-2">${escapeHtml(section.title)}</h3>
    ${renderSectionContent(section)}
  </div>`;
}

function renderSectionContent(section: DojoContentSection): string {
  switch (section.type) {
    case 'code':
      return `<pre class="bg-gray-50 dark:bg-gray-900 p-3 rounded text-sm overflow-x-auto"><code>${escapeHtml(section.content)}</code></pre>`;
    case 'checklist':
      return renderChecklist(section.content);
    case 'chart':
      return `<div class="overflow-x-auto">${section.content}</div>`;
    default:
      return `<div class="prose prose-sm dark:prose-invert max-w-none">${markdownToHtml(section.content)}</div>`;
  }
}

function renderChecklist(content: string): string {
  const items = content.split('\n').filter((l) => l.trim());
  return `<ul class="space-y-1">${items.map((item) => {
    const checked = item.startsWith('[x]') || item.startsWith('- [x]');
    const text = item.replace(/^[-*]?\s*\[[ x]\]\s*/, '');
    return `<li class="flex items-center gap-2 text-sm">
      <input type="checkbox" ${checked ? 'checked' : ''} class="rounded" disabled />
      <span${checked ? ' class="line-through text-gray-400"' : ''}>${escapeHtml(text)}</span>
    </li>`;
  }).join('')}</ul>`;
}

function sanitizeUrl(url: string): string {
  // Only allow http:, https:, and mailto: protocols
  const trimmed = url.trim();
  if (/^https?:/i.test(trimmed) || /^mailto:/i.test(trimmed)) {
    return trimmed;
  }
  return '#';
}

function markdownToHtml(md: string): string {
  // Pre-escape the entire markdown string to prevent XSS injection
  const escaped = escapeHtml(md);

  // Minimal markdown conversion — headings, bold, italic, links, paragraphs
  return escaped
    .replace(/^### (.+)$/gm, '<h4 class="font-semibold mt-3 mb-1">$1</h4>')
    .replace(/^## (.+)$/gm, '<h3 class="font-semibold mt-4 mb-2">$1</h3>')
    .replace(/^# (.+)$/gm, '<h2 class="font-bold mt-5 mb-2">$1</h2>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/\[(.+?)\]\((.+?)\)/g, (_match, text, href) => {
      const safeUrl = sanitizeUrl(href);
      return `<a href="${safeUrl}" class="text-dojo-sora hover:underline" target="_blank" rel="noopener">${text}</a>`;
    })
    .replace(/^- (.+)$/gm, '<li class="ml-4">$1</li>')
    .replace(/\n\n/g, '</p><p class="mt-2">')
    .replace(/^(?!<)(.+)$/gm, '<p class="mt-2">$1</p>');
}

function generateDarkModeScript(): string {
  return `(function(){
  if(window.matchMedia('(prefers-color-scheme: dark)').matches){
    document.documentElement.classList.add('dark');
  }
})();`;
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function slugify(str: string): string {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}
