import { z } from 'zod/v4';
import { StageCategorySchema } from './stage.js';

/**
 * What effect a rule has on a flavor's score during selection.
 */
export const RuleEffectSchema = z.enum(['boost', 'penalize', 'require', 'exclude']);
export type RuleEffect = z.infer<typeof RuleEffectSchema>;

/**
 * How the rule was created.
 */
export const RuleSourceSchema = z.enum(['auto-detected', 'user-created', 'imported']);
export type RuleSource = z.infer<typeof RuleSourceSchema>;

/**
 * A rule that influences flavor selection within a stage category.
 * Rules encode learned preferences — e.g. "in build stages for this project,
 * always boost the typescript-feature flavor when tests exist."
 */
export const StageRuleSchema = z.object({
  /** UUID identifying this rule. */
  id: z.string().uuid(),
  /** Which stage category this rule applies to. */
  category: StageCategorySchema,
  /** Human-readable name for the rule. */
  name: z.string().min(1),
  /** Human-readable condition description. */
  condition: z.string().min(1),
  /** What the rule does to a flavor's score. */
  effect: RuleEffectSchema,
  /** Strength of the effect, in [0, 1]. */
  magnitude: z.number().min(0).max(1),
  /** How confident we are in this rule, in [0, 1]. */
  confidence: z.number().min(0).max(1),
  /** How the rule was created. */
  source: RuleSourceSchema,
  /** Decision IDs or descriptions supporting this rule. */
  evidence: z.array(z.string()),
  /** ISO 8601 timestamp when the rule was created. */
  createdAt: z.string().datetime(),
});

export type StageRule = z.infer<typeof StageRuleSchema>;

/**
 * Status of a rule suggestion in the review workflow.
 */
export const RuleSuggestionStatusSchema = z.enum(['pending', 'accepted', 'rejected']);
export type RuleSuggestionStatus = z.infer<typeof RuleSuggestionStatusSchema>;

/**
 * A suggested rule generated by the self-improvement loop.
 * Suggestions are surfaced to the user for review before becoming active rules.
 */
export const RuleSuggestionSchema = z.object({
  /** UUID identifying this suggestion. */
  id: z.string().uuid(),
  /** The proposed rule without system-generated fields. */
  suggestedRule: StageRuleSchema.omit({ id: true, createdAt: true }),
  /** Decision IDs that led to this suggestion. */
  triggerDecisionIds: z.array(z.string().uuid()),
  /** How many times the pattern was observed. */
  observationCount: z.number().int().positive(),
  /** Why this rule is being suggested. */
  reasoning: z.string().min(1),
  /** Review status. */
  status: RuleSuggestionStatusSchema,
  /** User's edit notes if they modified the suggestion before accepting. */
  editDelta: z.string().optional(),
  /** Why the user rejected the suggestion. */
  rejectionReason: z.string().optional(),
  /** ISO 8601 timestamp when the suggestion was created. */
  createdAt: z.string().datetime(),
});

export type RuleSuggestion = z.infer<typeof RuleSuggestionSchema>;
