import { writeFileSync, existsSync, readFileSync } from 'node:fs';
import { basename } from 'node:path';
import { logger } from '@shared/lib/logger.js';

export interface AoConfigOptions {
  /** AO project key (defaults to packageName ?? basename(cwd)) */
  projectKey: string;
  /** Absolute path to the project root (repo root) */
  repoPath: string;
  /** Default branch for AO (defaults to 'main') */
  branch?: string;
  /** Output path for the generated config file */
  outputPath: string;
}

/**
 * Escape a value for use as a YAML single-quoted scalar.
 * Single-quotes inside the value are doubled: ' → ''
 */
function yamlQuote(val: string): string {
  return `'${val.replace(/'/g, "''")}'`;
}

/**
 * Generate a minimal agent-orchestrator.yaml entry for Kata projects.
 *
 * We emit only the fields we've validated work with @composio/ao-core v0.1.x.
 * This is written to .kata/ao-config.yaml to keep it separate from any
 * user-managed agent-orchestrator.yaml at the project root.
 */
export function generateAoConfig(options: AoConfigOptions): void {
  const { projectKey, repoPath, branch = 'main', outputPath } = options;

  const yaml = [
    '# Generated by kata init — do not edit by hand.',
    '# See: https://github.com/ComposioHQ/agent-orchestrator',
    '# Validated against @composio/ao-core v0.1.x',
    '#',
    '# Pass this file to ComposioAdapter via:',
    '#   execution.config.aoConfigPath in .kata/config.json',
    '',
    'projects:',
    `  ${yamlQuote(projectKey)}:`,
    `    repo: ${yamlQuote(repoPath)}`,
    `    branch: ${yamlQuote(branch)}`,
    `    symlinks:`,
    `      - .kata`,
    '',
  ].join('\n');

  writeFileSync(outputPath, yaml, 'utf-8');
}

/**
 * Detect the current git branch in the given directory.
 * Returns 'main' as a safe fallback.
 */
export function detectGitBranch(cwd: string): string {
  try {
    const headPath = `${cwd}/.git/HEAD`;
    if (!existsSync(headPath)) return 'main';
    const head = readFileSync(headPath, 'utf-8').trim();
    // "ref: refs/heads/main" → "main"
    const match = head.match(/^ref: refs\/heads\/(.+)$/);
    if (!match) {
      logger.warn(`detectGitBranch: HEAD is not a branch ref (detached HEAD?) in "${cwd}". Defaulting to 'main' in ao-config.yaml.`);
      return 'main';
    }
    return match[1] ?? 'main';
  } catch (err) {
    logger.warn(`detectGitBranch: could not read .git/HEAD in "${cwd}": ${err instanceof Error ? err.message : String(err)}. Defaulting to 'main' in ao-config.yaml.`);
    return 'main';
  }
}

/**
 * Derive the AO project key from the package name or directory basename.
 */
export function deriveProjectKey(packageName: string | undefined, cwd: string): string {
  return packageName ?? basename(cwd);
}
